name: plus
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  benchmark_harness: "any"
  logging: "any"

# custom <plus dependencies>

  ebisu:
    git: git://github.com/patefacio/ebisu

  ebisu_web_ui:
    git: git://github.com/patefacio/ebisu_web_ui

  json_schema:
    git: git://github.com/patefacio/json_schema

  simple_schema:
    git: git://github.com/patefacio/simple_schema

  basic_input:
    path: ../component_libs/basic_input

# end <plus dependencies>

dev_dependencies:
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <plus dev dependencies>

# end <plus dev dependencies>

dependency_overrides:
# custom <plus dependency overrides>
# end <plus dependency overrides>

transformers:

# custom <plus transformers>
# end <plus transformers>

