name: plus
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <plus dependencies>

  ebisu:
    git: git://github.com/patefacio/ebisu

# end <plus dependencies>

dev_dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <plus dev dependencies>

# end <plus dev dependencies>

transformers:

# custom <plus transformers>
# end <plus transformers>

