name: basic_input
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  logging: ">=0.9.2 <0.10.0"

# custom <basic_input dependencies>

  polymer: ">=0.15.0"
  collection: ">=1.0.0"
  paper_elements: ">=0.4.0"
  core_elements: ">=0.2.0+1"
  intl: ">=0.11.9"

# end <basic_input dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"

# custom <basic_input dev dependencies>
# end <basic_input dev dependencies>

transformers:
  - polymer:
      entry_points:
        - web/examples/basic_input/basic_input.html

# custom <basic_input transformers>
# end <basic_input transformers>

